insert into product (productID, productName, imageUrl, amount, currency) values (1, 'FENTORA', 'https://picsum.photos/id/522/400', 2162, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (2, 'Ampicillin and Sulbactam', 'https://picsum.photos/id/598/400', 4955, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (3, 'alendronate sodium', 'https://picsum.photos/id/642/400', 2196, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (4, 'CETIRIZINE HYDROCHLORIDE', 'https://picsum.photos/id/489/400', 4666, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (5, 'Aspergillus terreus', 'https://picsum.photos/id/408/400', 2195, 'Marka');
insert into product (productID, productName, imageUrl, amount, currency) values (6, 'Terbinafine Hydrochloride', 'https://picsum.photos/id/462/400', 2787, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (7, 'BareMinerals', 'https://picsum.photos/id/279/400', 1900, 'Quetzal');
insert into product (productID, productName, imageUrl, amount, currency) values (8, 'Hydromorphone HCl', 'https://picsum.photos/id/451/400', 1970, 'Sol');
insert into product (productID, productName, imageUrl, amount, currency) values (9, 'LANOXIN', 'https://picsum.photos/id/147/400', 4722, 'Bolivar');
insert into product (productID, productName, imageUrl, amount, currency) values (10, 'Pollens - Weeds and Garden Plants, Lamb Quarters Chenopodium album', 'https://picsum.photos/id/329/400', 2024, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (11, 'Hypericum Perf Kit Refill', 'https://picsum.photos/id/195/400', 4075, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (12, 'Mirapex', 'https://picsum.photos/id/430/400', 3852, 'Naira');
insert into product (productID, productName, imageUrl, amount, currency) values (13, 'Pramipexole Dihydrochloride', 'https://picsum.photos/id/445/400', 4803, 'Franc');
insert into product (productID, productName, imageUrl, amount, currency) values (14, 'LISINOPRIL', 'https://picsum.photos/id/543/400', 747, 'Zloty');
insert into product (productID, productName, imageUrl, amount, currency) values (15, 'NICORETTE', 'https://picsum.photos/id/300/400', 1153, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (16, 'Cardene I.V.', 'https://picsum.photos/id/386/400', 3576, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (17, 'Eczemol', 'https://picsum.photos/id/69/400', 2041, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (18, 'Triple Antibiotic', 'https://picsum.photos/id/696/400', 3052, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (19, 'MANICURE BY OPI - FINISHING BUTTER', 'https://picsum.photos/id/221/400', 199, 'Krona');
insert into product (productID, productName, imageUrl, amount, currency) values (20, 'Doxycycline Hyclate', 'https://picsum.photos/id/318/400', 4787, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (21, 'Leader Chest Congestion Relief Plus DMDM', 'https://picsum.photos/id/582/400', 3495, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (22, 'Haloperidol', 'https://picsum.photos/id/537/400', 4951, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (23, 'Lightening Serum', 'https://picsum.photos/id/545/400', 1747, 'Rupee');
insert into product (productID, productName, imageUrl, amount, currency) values (24, 'heartburn prevention', 'https://picsum.photos/id/659/400', 3360, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (25, 'Rohto Hydra', 'https://picsum.photos/id/103/400', 2585, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (26, 'Secret Hawaii Invisible', 'https://picsum.photos/id/124/400', 307, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (27, 'Metoprolol Tartrate', 'https://picsum.photos/id/267/400', 1905, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (28, 'Zanaflex', 'https://picsum.photos/id/632/400', 4159, 'Zloty');
insert into product (productID, productName, imageUrl, amount, currency) values (29, 'LBEL', 'https://picsum.photos/id/650/400', 1174, 'Lev');
insert into product (productID, productName, imageUrl, amount, currency) values (30, 'CVS Medicated Anti-Itch', 'https://picsum.photos/id/317/400', 955, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (31, 'Ticlopidine Hydrochloride', 'https://picsum.photos/id/220/400', 3357, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (32, 'Ibuprofen', 'https://picsum.photos/id/229/400', 2607, 'Zloty');
insert into product (productID, productName, imageUrl, amount, currency) values (33, 'equate nitetime', 'https://picsum.photos/id/606/400', 3300, 'Yen');
insert into product (productID, productName, imageUrl, amount, currency) values (34, 'Heeltastic', 'https://picsum.photos/id/225/400', 688, 'Sol');
insert into product (productID, productName, imageUrl, amount, currency) values (35, 'Family Care Hemorrhoidal', 'https://picsum.photos/id/339/400', 2631, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (36, 'ATORVASTATIN CALCIUM', 'https://picsum.photos/id/261/400', 48, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (37, 'Listerine HealthyWhite Anticavity Mouthrinse Vibrant - Clean Mint', 'https://picsum.photos/id/430/400', 3434, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (38, 'Black Locust', 'https://picsum.photos/id/682/400', 4323, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (39, 'OLANZAPINE', 'https://picsum.photos/id/21/400', 4427, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (40, 'Hydromorphone HCl', 'https://picsum.photos/id/680/400', 1698, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (41, 'Ear Drops', 'https://picsum.photos/id/202/400', 2842, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (42, 'Hand Sanitizer', 'https://picsum.photos/id/39/400', 4694, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (43, 'Antibacterial Foaming Hand Cleanser', 'https://picsum.photos/id/39/400', 2056, 'Zloty');
insert into product (productID, productName, imageUrl, amount, currency) values (44, 'Valacyclovir Hydrochloride', 'https://picsum.photos/id/226/400', 335, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (45, 'Hydrogen Peroxide', 'https://picsum.photos/id/537/400', 1147, 'Franc');
insert into product (productID, productName, imageUrl, amount, currency) values (46, 'SkinCeuticals Physical UV Defense Broad Spectrum SPF 30 Sunscreen', 'https://picsum.photos/id/428/400', 1287, 'Dram');
insert into product (productID, productName, imageUrl, amount, currency) values (47, 'healthy accents enema', 'https://picsum.photos/id/324/400', 1729, 'Rial');
insert into product (productID, productName, imageUrl, amount, currency) values (48, 'Fear Phobia', 'https://picsum.photos/id/155/400', 2234, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (49, 'HepaGam B', 'https://picsum.photos/id/426/400', 4758, 'Quetzal');
insert into product (productID, productName, imageUrl, amount, currency) values (50, 'Hydroxyzine Hydrochloride', 'https://picsum.photos/id/511/400', 2498, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (51, 'Absorica', 'https://picsum.photos/id/549/400', 3960, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (52, 'Topcare Headache PM Formula', 'https://picsum.photos/id/507/400', 4886, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (53, 'Zolpidem Tartrate', 'https://picsum.photos/id/122/400', 4566, 'Tala');
insert into product (productID, productName, imageUrl, amount, currency) values (54, 'Doxepin Hydrochloride', 'https://picsum.photos/id/306/400', 3432, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (55, 'Cefprozil', 'https://picsum.photos/id/307/400', 2809, 'Boliviano');
insert into product (productID, productName, imageUrl, amount, currency) values (56, 'Afrin', 'https://picsum.photos/id/189/400', 2923, 'Shekel');
insert into product (productID, productName, imageUrl, amount, currency) values (57, 'DOLOPHINE HYDROCHLORIDE', 'https://picsum.photos/id/372/400', 2797, 'Koruna');
insert into product (productID, productName, imageUrl, amount, currency) values (58, 'Gentak', 'https://picsum.photos/id/185/400', 3176, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (59, 'EUCALYPTUS GLOBULUS POLLEN', 'https://picsum.photos/id/522/400', 1455, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (60, 'CD DIORSKIN STAR Studio Makeup Spectacular Brightening with sunscreen Broad Spectrum SPF30 030', 'https://picsum.photos/id/649/400', 3208, 'Rupee');
insert into product (productID, productName, imageUrl, amount, currency) values (61, 'Tilia Fe', 'https://picsum.photos/id/261/400', 3363, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (62, 'Cialis', 'https://picsum.photos/id/552/400', 2591, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (63, 'CYPROHEPTADINE HYDROCHLORIDE', 'https://picsum.photos/id/178/400', 1047, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (64, 'Ammonia N 13', 'https://picsum.photos/id/84/400', 3833, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (65, 'Atracurium Besylate', 'https://picsum.photos/id/372/400', 2695, 'Quetzal');
insert into product (productID, productName, imageUrl, amount, currency) values (66, 'LOESTRIN Fe 1/20', 'https://picsum.photos/id/241/400', 4106, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (67, 'voriconazole', 'https://picsum.photos/id/437/400', 2938, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (68, 'Amlodipine and Atorvastatin', 'https://picsum.photos/id/664/400', 1050, 'Franc');
insert into product (productID, productName, imageUrl, amount, currency) values (69, 'Pollens - Grasses, Southern Grass Mix', 'https://picsum.photos/id/626/400', 2665, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (70, 'Sodium Acetate', 'https://picsum.photos/id/402/400', 516, 'Krona');
insert into product (productID, productName, imageUrl, amount, currency) values (71, 'Fluphenazine Hydrochloride', 'https://picsum.photos/id/645/400', 105, 'Leone');
insert into product (productID, productName, imageUrl, amount, currency) values (72, 'ZONISAMIDE', 'https://picsum.photos/id/103/400', 3116, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (73, 'Methylprednisolone', 'https://picsum.photos/id/662/400', 2532, 'Dram');
insert into product (productID, productName, imageUrl, amount, currency) values (74, 'medroxyprogesterone acetate', 'https://picsum.photos/id/520/400', 4624, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (75, 'Oxygen', 'https://picsum.photos/id/180/400', 4583, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (76, 'Diaper Rash', 'https://picsum.photos/id/416/400', 649, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (77, 'Tree Mixture', 'https://picsum.photos/id/265/400', 2512, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (78, 'Escitalopram oxalate', 'https://picsum.photos/id/532/400', 4887, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (79, 'ARTEMISIA TRIDENTATA POLLEN', 'https://picsum.photos/id/454/400', 2729, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (80, 'Oil Free Matte', 'https://picsum.photos/id/63/400', 4910, 'Hryvnia');
insert into product (productID, productName, imageUrl, amount, currency) values (81, 'Atorvastatin Calcium', 'https://picsum.photos/id/463/400', 641, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (82, 'pain relief', 'https://picsum.photos/id/92/400', 1625, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (83, 'Coffea cruda', 'https://picsum.photos/id/604/400', 4498, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (84, 'Silver Maple', 'https://picsum.photos/id/115/400', 2523, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (85, 'azithromycin', 'https://picsum.photos/id/112/400', 3300, 'Baht');
insert into product (productID, productName, imageUrl, amount, currency) values (86, 'Hand Sanitizer', 'https://picsum.photos/id/417/400', 3250, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (87, 'Pleo Nig', 'https://picsum.photos/id/553/400', 35, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (88, 'Freds Hemorrhoidal', 'https://picsum.photos/id/193/400', 1906, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (89, 'ACETAMINOPHEN AND CODEINE PHOSPHATE', 'https://picsum.photos/id/163/400', 4967, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (90, 'DELFLEX', 'https://picsum.photos/id/67/400', 1063, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (91, 'No7 Restore and Renew Day Sunscreen', 'https://picsum.photos/id/393/400', 4936, 'Pound');
insert into product (productID, productName, imageUrl, amount, currency) values (92, 'Stila Hydrating Primer Oil-Free SPF 30', 'https://picsum.photos/id/259/400', 2232, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (93, 'PENICILLIUM CHRYSOGENUM VAR CHRYSOGENUM', 'https://picsum.photos/id/260/400', 4185, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (94, 'Lorazepam', 'https://picsum.photos/id/334/400', 4766, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (95, 'Fiber Lax', 'https://picsum.photos/id/120/400', 1071, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (96, 'Ibuprofen', 'https://picsum.photos/id/135/400', 4608, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (97, 'Elta Tar', 'https://picsum.photos/id/159/400', 120, 'Lev');
insert into product (productID, productName, imageUrl, amount, currency) values (98, 'Cranberry', 'https://picsum.photos/id/134/400', 1875, 'Baht');
insert into product (productID, productName, imageUrl, amount, currency) values (99, 'Albumin (Human)', 'https://picsum.photos/id/409/400', 4505, 'Lek');
insert into product (productID, productName, imageUrl, amount, currency) values (100, 'Hydroxyzine Pamoate', 'https://picsum.photos/id/668/400', 1853, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (101, 'ICS PERFECT SOLUTION', 'https://picsum.photos/id/687/400', 517, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (102, 'cetylpyridinium chloride', 'https://picsum.photos/id/390/400', 363, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (103, 'Uramaxin', 'https://picsum.photos/id/290/400', 2347, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (104, 'McKesson Skin Protectant', 'https://picsum.photos/id/146/400', 4235, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (105, 'Ativan', 'https://picsum.photos/id/270/400', 324, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (106, 'Effervescent Potassium Chloride', 'https://picsum.photos/id/101/400', 1824, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (107, 'SCREAMIN MENTHOL TOAST', 'https://picsum.photos/id/558/400', 4998, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (108, 'LBEL NATURAL FINISH MOISTURIZING FOUNDATION SPF 25', 'https://picsum.photos/id/380/400', 4735, 'Cordoba');
insert into product (productID, productName, imageUrl, amount, currency) values (109, 'Adidas 24H Anti Perspirant', 'https://picsum.photos/id/638/400', 1327, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (110, 'LIPODOX', 'https://picsum.photos/id/354/400', 4416, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (111, 'health mart acid reducer', 'https://picsum.photos/id/16/400', 4749, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (112, 'Alprazolam', 'https://picsum.photos/id/17/400', 2654, 'Yen');
insert into product (productID, productName, imageUrl, amount, currency) values (113, 'ABILIFY', 'https://picsum.photos/id/473/400', 868, 'Koruna');
insert into product (productID, productName, imageUrl, amount, currency) values (114, 'Berkley and Jensen Nasal Decongestant PE', 'https://picsum.photos/id/520/400', 1157, 'Denar');
insert into product (productID, productName, imageUrl, amount, currency) values (115, 'Venlafaxine Hydrochloride', 'https://picsum.photos/id/463/400', 253, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (116, 'Rimantadine Hydrochloride', 'https://picsum.photos/id/138/400', 1911, 'Krona');
insert into product (productID, productName, imageUrl, amount, currency) values (117, 'OXYBUTYNIN CHLORIDE', 'https://picsum.photos/id/28/400', 4877, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (118, 'shoprite mucus relief', 'https://picsum.photos/id/485/400', 2965, 'Tenge');
insert into product (productID, productName, imageUrl, amount, currency) values (119, 'Dove', 'https://picsum.photos/id/442/400', 2954, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (120, 'Lisinopril', 'https://picsum.photos/id/388/400', 3143, 'Krona');
insert into product (productID, productName, imageUrl, amount, currency) values (121, 'Mickey Sun Smacker SPF 24 Classic Vanilla', 'https://picsum.photos/id/648/400', 4348, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (122, 'Immune Support Junior Strength', 'https://picsum.photos/id/230/400', 818, 'Lempira');
insert into product (productID, productName, imageUrl, amount, currency) values (123, 'Jet Lag', 'https://picsum.photos/id/135/400', 3467, 'Dinar');
insert into product (productID, productName, imageUrl, amount, currency) values (124, 'Ramipril', 'https://picsum.photos/id/89/400', 319, 'Yen');
insert into product (productID, productName, imageUrl, amount, currency) values (125, 'ShopRite Acid Reducer', 'https://picsum.photos/id/619/400', 1741, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (126, 'Melaleuca Pollen', 'https://picsum.photos/id/521/400', 1777, 'Baht');
insert into product (productID, productName, imageUrl, amount, currency) values (127, 'Lamotrigine', 'https://picsum.photos/id/628/400', 2684, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (128, 'Sweet Papaya Antibacterial Foaming Hand Wash', 'https://picsum.photos/id/344/400', 1460, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (129, 'Threefold Balance', 'https://picsum.photos/id/114/400', 3086, 'Rial');
insert into product (productID, productName, imageUrl, amount, currency) values (130, 'Oxycodone and Acetaminophen', 'https://picsum.photos/id/531/400', 2338, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (131, 'Kaletra', 'https://picsum.photos/id/647/400', 1107, 'Zloty');
insert into product (productID, productName, imageUrl, amount, currency) values (132, 'Thario Instant Hand Sanitizer', 'https://picsum.photos/id/181/400', 2698, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (133, 'Methocarbamol', 'https://picsum.photos/id/181/400', 1906, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (134, 'Levofloxacin', 'https://picsum.photos/id/195/400', 4001, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (135, 'Pioglitazone Hydrochloride', 'https://picsum.photos/id/78/400', 1582, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (136, 'Arnica e pl. tota 20', 'https://picsum.photos/id/153/400', 4793, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (137, 'Loratadine', 'https://picsum.photos/id/499/400', 1525, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (138, 'Pleo San Serra', 'https://picsum.photos/id/571/400', 3437, 'Dram');
insert into product (productID, productName, imageUrl, amount, currency) values (139, 'FIRMAGON', 'https://picsum.photos/id/20/400', 1424, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (140, 'Siltussin DM DAS Cough Formula', 'https://picsum.photos/id/204/400', 3621, 'Rand');
insert into product (productID, productName, imageUrl, amount, currency) values (141, 'miconazole 1', 'https://picsum.photos/id/316/400', 1774, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (142, 'Spiced Cider Antibacterial Foaming Hand Wash', 'https://picsum.photos/id/525/400', 3935, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (143, 'ESIKA HD COLOR HIGH DEFINITION COLOR SPF 20', 'https://picsum.photos/id/495/400', 2812, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (144, 'Ciprofloxacin', 'https://picsum.photos/id/299/400', 2621, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (145, 'good neighbor pharmacy nicotine', 'https://picsum.photos/id/32/400', 121, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (146, 'amlodipine besylate and atorvastatin calcium', 'https://picsum.photos/id/276/400', 2651, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (147, 'pain relief', 'https://picsum.photos/id/583/400', 2999, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (148, 'Tirosint', 'https://picsum.photos/id/647/400', 1633, 'Yen');
insert into product (productID, productName, imageUrl, amount, currency) values (149, 'ERAXIS', 'https://picsum.photos/id/619/400', 2530, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (150, 'Sertraline Hydrochloride', 'https://picsum.photos/id/236/400', 1507, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (151, 'Citalopram', 'https://picsum.photos/id/41/400', 3203, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (152, 'Allergy', 'https://picsum.photos/id/536/400', 2639, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (153, 'Medpride', 'https://picsum.photos/id/609/400', 1991, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (154, 'Echinacea Thuja Special Order', 'https://picsum.photos/id/232/400', 3327, 'Hryvnia');
insert into product (productID, productName, imageUrl, amount, currency) values (155, 'Hydrocortisone Maximum Strength Plus 12 Moisturizers', 'https://picsum.photos/id/307/400', 4570, 'Baht');
insert into product (productID, productName, imageUrl, amount, currency) values (156, 'Good Sense Muscle', 'https://picsum.photos/id/121/400', 2640, 'Pound');
insert into product (productID, productName, imageUrl, amount, currency) values (157, 'ARTEMISIA TRIDENTATA POLLEN', 'https://picsum.photos/id/13/400', 4397, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (158, 'Neutrogena Healthy Skin Makeup', 'https://picsum.photos/id/107/400', 4757, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (159, 'Lisinopril', 'https://picsum.photos/id/202/400', 1618, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (160, 'WAL-DRYL ALLERGY', 'https://picsum.photos/id/313/400', 4024, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (161, 'Tonic', 'https://picsum.photos/id/336/400', 4005, 'Dinar');
insert into product (productID, productName, imageUrl, amount, currency) values (162, 'PRAVASTATIN SODIUM', 'https://picsum.photos/id/526/400', 1548, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (163, 'Citanest Forte', 'https://picsum.photos/id/76/400', 806, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (164, 'Carvedilol', 'https://picsum.photos/id/207/400', 1223, 'Sol');
insert into product (productID, productName, imageUrl, amount, currency) values (165, 'Leader Antacid', 'https://picsum.photos/id/74/400', 4761, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (166, 'Fentanyl Citrate', 'https://picsum.photos/id/470/400', 3465, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (167, 'Publix Kids', 'https://picsum.photos/id/326/400', 4828, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (168, 'Ibuprofen', 'https://picsum.photos/id/625/400', 3961, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (169, 'JAFRA PRO FACE LIFT', 'https://picsum.photos/id/558/400', 2303, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (170, 'ECZEMA', 'https://picsum.photos/id/670/400', 2491, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (171, 'Yellow Birch', 'https://picsum.photos/id/5/400', 2083, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (172, 'GRAPE', 'https://picsum.photos/id/599/400', 3205, 'Ringgit');
insert into product (productID, productName, imageUrl, amount, currency) values (173, 'Tinted Moisturizer Matte Broad Spectrum SPF 45', 'https://picsum.photos/id/127/400', 1730, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (174, 'Metoprolol Tartrate', 'https://picsum.photos/id/177/400', 4685, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (175, 'Gentle Laxative', 'https://picsum.photos/id/631/400', 1458, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (176, 'omeprazole', 'https://picsum.photos/id/680/400', 1292, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (177, 'Venlafaxine Hydrochloride', 'https://picsum.photos/id/71/400', 3762, 'Hryvnia');
insert into product (productID, productName, imageUrl, amount, currency) values (178, 'Olay Regenerist', 'https://picsum.photos/id/379/400', 239, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (179, 'Fosinopril sodium', 'https://picsum.photos/id/507/400', 3862, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (180, 'Stay Awake', 'https://picsum.photos/id/611/400', 1459, 'Rand');
insert into product (productID, productName, imageUrl, amount, currency) values (181, 'Labetalol Hydrochloride', 'https://picsum.photos/id/528/400', 448, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (182, 'TONYMOLY FLORIA WHITENING ESSENCE', 'https://picsum.photos/id/608/400', 209, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (183, 'fluocinonide', 'https://picsum.photos/id/425/400', 1170, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (184, 'Antibacterial Foaming Hand Sanitizer', 'https://picsum.photos/id/301/400', 4059, 'Rial');
insert into product (productID, productName, imageUrl, amount, currency) values (185, 'NASOPEN', 'https://picsum.photos/id/251/400', 4001, 'Hryvnia');
insert into product (productID, productName, imageUrl, amount, currency) values (186, 'amlodipine besylate and atorvastatin calcium', 'https://picsum.photos/id/288/400', 3009, 'Koruna');
insert into product (productID, productName, imageUrl, amount, currency) values (187, 'Hand Guard Foaming Antimicrobial', 'https://picsum.photos/id/394/400', 3901, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (188, 'Leader tussin dm max', 'https://picsum.photos/id/204/400', 187, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (189, 'Leader Restfully Sleep', 'https://picsum.photos/id/554/400', 3507, 'Lempira');
insert into product (productID, productName, imageUrl, amount, currency) values (190, 'Nabumetone', 'https://picsum.photos/id/662/400', 2706, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (191, 'Quinapril Hydrochloride and Hydrochlorothiazide', 'https://picsum.photos/id/470/400', 274, 'Lempira');
insert into product (productID, productName, imageUrl, amount, currency) values (192, 'Metformin Hydrochloride', 'https://picsum.photos/id/370/400', 2016, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (193, 'RISPERIDONE', 'https://picsum.photos/id/611/400', 740, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (194, 'Neutrogena Shine Control Makeup', 'https://picsum.photos/id/50/400', 1597, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (195, 'Gold Bond Medicated Foot', 'https://picsum.photos/id/17/400', 3503, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (196, 'Metformin Hydrochloride', 'https://picsum.photos/id/375/400', 1156, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (197, 'Atralin', 'https://picsum.photos/id/357/400', 1359, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (198, 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 'https://picsum.photos/id/645/400', 3930, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (199, 'Magnesium Citrate', 'https://picsum.photos/id/44/400', 2854, 'Franc');
insert into product (productID, productName, imageUrl, amount, currency) values (200, 'Mirtazapine', 'https://picsum.photos/id/478/400', 4482, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (201, 'IPKN Moist and Firm BB 01 Light', 'https://picsum.photos/id/163/400', 2920, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (202, 'Lansoprazole', 'https://picsum.photos/id/653/400', 2379, 'Koruna');
insert into product (productID, productName, imageUrl, amount, currency) values (203, 'Care One Maximum Strength First Aid Antibiotic', 'https://picsum.photos/id/204/400', 3513, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (204, 'Venlafaxine Hydrochloride', 'https://picsum.photos/id/661/400', 3402, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (205, 'Acyclovir', 'https://picsum.photos/id/62/400', 2007, 'Krona');
insert into product (productID, productName, imageUrl, amount, currency) values (206, 'Baclofen', 'https://picsum.photos/id/576/400', 1005, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (207, 'Colestid', 'https://picsum.photos/id/528/400', 4192, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (208, 'Bacitracin', 'https://picsum.photos/id/187/400', 3616, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (209, 'BANANA BOAT', 'https://picsum.photos/id/462/400', 3112, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (210, 'Amlodipine Besylate', 'https://picsum.photos/id/492/400', 1010, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (211, 'Buspirone Hydrochloride', 'https://picsum.photos/id/237/400', 3973, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (212, 'Multi-Symptom Cold Relief', 'https://picsum.photos/id/339/400', 3874, 'Zloty');
insert into product (productID, productName, imageUrl, amount, currency) values (213, 'Hydrating and Balancing Moisturizer', 'https://picsum.photos/id/247/400', 4907, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (214, 'Monilia Mixture', 'https://picsum.photos/id/496/400', 3285, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (215, 'Bal-Care DHA Essential', 'https://picsum.photos/id/191/400', 3133, 'Naira');
insert into product (productID, productName, imageUrl, amount, currency) values (216, 'Glyburide', 'https://picsum.photos/id/30/400', 4876, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (217, 'First Aid Direct Buffered Eyewash Sterile Isotonic', 'https://picsum.photos/id/229/400', 3839, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (218, 'Cefazolin', 'https://picsum.photos/id/292/400', 4090, 'Dinar');
insert into product (productID, productName, imageUrl, amount, currency) values (219, 'Aurum 30', 'https://picsum.photos/id/570/400', 4434, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (220, 'Cephalexin', 'https://picsum.photos/id/311/400', 2118, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (221, 'Pleo Fort', 'https://picsum.photos/id/568/400', 4993, 'Zloty');
insert into product (productID, productName, imageUrl, amount, currency) values (222, 'Fluconazole', 'https://picsum.photos/id/207/400', 566, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (223, 'Eczema Skin Care', 'https://picsum.photos/id/143/400', 2809, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (224, 'Doxycycline Hyclate', 'https://picsum.photos/id/88/400', 570, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (225, 'Erythromycin', 'https://picsum.photos/id/210/400', 1924, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (226, 'Anti-Bacterial Hand Sanitizer', 'https://picsum.photos/id/627/400', 1628, 'Boliviano');
insert into product (productID, productName, imageUrl, amount, currency) values (227, 'Treatment Set TS333308', 'https://picsum.photos/id/576/400', 869, 'Baht');
insert into product (productID, productName, imageUrl, amount, currency) values (228, 'Lipitor', 'https://picsum.photos/id/392/400', 1730, 'Ringgit');
insert into product (productID, productName, imageUrl, amount, currency) values (229, 'Fusarium compactum', 'https://picsum.photos/id/574/400', 2113, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (230, 'ORAL-DENT', 'https://picsum.photos/id/645/400', 4104, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (231, 'Complexion Perfector BB SPF20', 'https://picsum.photos/id/106/400', 2051, 'Naira');
insert into product (productID, productName, imageUrl, amount, currency) values (232, 'Azelastine Hydrochloride', 'https://picsum.photos/id/343/400', 2021, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (233, 'Metoprolol Tartrate', 'https://picsum.photos/id/209/400', 473, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (234, 'BUPRENORPHINE HYDROCHLORIDE', 'https://picsum.photos/id/152/400', 4332, 'Lek');
insert into product (productID, productName, imageUrl, amount, currency) values (235, 'Haloperidol', 'https://picsum.photos/id/414/400', 4305, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (236, 'Blackeye Pea', 'https://picsum.photos/id/49/400', 2148, 'Kyat');
insert into product (productID, productName, imageUrl, amount, currency) values (237, 'ZENPEP', 'https://picsum.photos/id/646/400', 309, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (238, 'Theracodeine-300', 'https://picsum.photos/id/675/400', 4349, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (239, 'Bioxsine Series', 'https://picsum.photos/id/513/400', 19, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (240, 'IMBRUVICA', 'https://picsum.photos/id/152/400', 2620, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (241, 'Ketoconazole', 'https://picsum.photos/id/385/400', 2779, 'Yen');
insert into product (productID, productName, imageUrl, amount, currency) values (242, 'Pretty in Paris Hand Sanitizer', 'https://picsum.photos/id/581/400', 4118, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (243, 'Fluconazole', 'https://picsum.photos/id/184/400', 14, 'Yen');
insert into product (productID, productName, imageUrl, amount, currency) values (244, 'Carroll Ultrex Antimicrobial Wipes', 'https://picsum.photos/id/311/400', 2075, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (245, 'Fosinopril Sodium', 'https://picsum.photos/id/640/400', 4651, 'Baht');
insert into product (productID, productName, imageUrl, amount, currency) values (246, 'CALIFORNIA ALOE OIL FREE SUN BLOCK', 'https://picsum.photos/id/182/400', 1037, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (247, 'Oxymorphone Hydrochloride', 'https://picsum.photos/id/85/400', 1637, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (248, 'VECURONIUM BROMIDE', 'https://picsum.photos/id/567/400', 4749, 'Krone');
insert into product (productID, productName, imageUrl, amount, currency) values (249, 'Pioglitazone Hydrochloride', 'https://picsum.photos/id/546/400', 4995, 'Hryvnia');
insert into product (productID, productName, imageUrl, amount, currency) values (250, 'ADVATE', 'https://picsum.photos/id/649/400', 794, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (251, 'Simvastatin', 'https://picsum.photos/id/207/400', 85, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (252, 'Buspirone HCl', 'https://picsum.photos/id/507/400', 3961, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (253, 'COLTALIN-ND', 'https://picsum.photos/id/18/400', 925, 'Dinar');
insert into product (productID, productName, imageUrl, amount, currency) values (254, 'Blackeye Pea', 'https://picsum.photos/id/90/400', 4693, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (255, 'Naproxen Sodium', 'https://picsum.photos/id/135/400', 3506, 'Afghani');
insert into product (productID, productName, imageUrl, amount, currency) values (256, 'RISPERIDONE', 'https://picsum.photos/id/332/400', 251, 'Rial');
insert into product (productID, productName, imageUrl, amount, currency) values (257, 'miconazole 3', 'https://picsum.photos/id/324/400', 3430, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (258, 'TAMSULOSIN HYDROCHLORIDE', 'https://picsum.photos/id/401/400', 1776, 'Hryvnia');
insert into product (productID, productName, imageUrl, amount, currency) values (259, 'METHAZOLAMIDE', 'https://picsum.photos/id/316/400', 425, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (260, 'Xopenex', 'https://picsum.photos/id/74/400', 2158, 'Taka');
insert into product (productID, productName, imageUrl, amount, currency) values (261, 'Curly Dock', 'https://picsum.photos/id/321/400', 1382, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (262, 'ShopKo Absolute Daily Moisturizing Broad Spectrum SPF15 Sunscreen', 'https://picsum.photos/id/363/400', 98, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (263, 'Levothyroxine Sodium', 'https://picsum.photos/id/237/400', 2217, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (264, 'Amlodipine Besylate', 'https://picsum.photos/id/183/400', 1231, 'Shekel');
insert into product (productID, productName, imageUrl, amount, currency) values (265, 'Naproxen', 'https://picsum.photos/id/32/400', 2294, 'Krona');
insert into product (productID, productName, imageUrl, amount, currency) values (266, 'Loperamide Hydrochloride', 'https://picsum.photos/id/94/400', 1079, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (267, 'Hydrochlorothiazide', 'https://picsum.photos/id/113/400', 2625, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (268, 'Nifedipine', 'https://picsum.photos/id/66/400', 1495, 'Boliviano');
insert into product (productID, productName, imageUrl, amount, currency) values (269, 'Health Mart Ibuprofen IB', 'https://picsum.photos/id/462/400', 2249, 'Zloty');
insert into product (productID, productName, imageUrl, amount, currency) values (270, 'Perindopril Erbumine', 'https://picsum.photos/id/409/400', 4115, 'Kwacha');
insert into product (productID, productName, imageUrl, amount, currency) values (271, 'Mesquite', 'https://picsum.photos/id/35/400', 456, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (272, 'Senna and Docusate Sodium', 'https://picsum.photos/id/445/400', 3981, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (273, 'Vancocin', 'https://picsum.photos/id/112/400', 3905, 'Krona');
insert into product (productID, productName, imageUrl, amount, currency) values (274, 'Hydralazine Hydrochloride', 'https://picsum.photos/id/413/400', 606, 'Zloty');
insert into product (productID, productName, imageUrl, amount, currency) values (275, 'FLUOXETINE', 'https://picsum.photos/id/385/400', 3863, 'Hryvnia');
insert into product (productID, productName, imageUrl, amount, currency) values (276, 'Rimmel BB Cream Matte 9-IN-1 Skin Perfecting Super Makeup', 'https://picsum.photos/id/700/400', 1880, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (277, 'RITEAID HEMORRHOIDAL COOLING', 'https://picsum.photos/id/526/400', 2535, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (278, 'morphine sulfate', 'https://picsum.photos/id/47/400', 2929, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (279, 'Amazing Face', 'https://picsum.photos/id/396/400', 2542, 'Dinar');
insert into product (productID, productName, imageUrl, amount, currency) values (280, 'Fenofibrate', 'https://picsum.photos/id/196/400', 2531, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (281, 'Atovaquone and Proguanil Hydrochloride', 'https://picsum.photos/id/123/400', 4837, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (282, 'Budeprion', 'https://picsum.photos/id/332/400', 5, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (283, 'Foaming Hand Wash', 'https://picsum.photos/id/516/400', 4800, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (284, 'Temovate', 'https://picsum.photos/id/194/400', 467, 'Yen');
insert into product (productID, productName, imageUrl, amount, currency) values (285, 'Lovenox', 'https://picsum.photos/id/697/400', 1063, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (286, 'Heparin Sodium', 'https://picsum.photos/id/674/400', 3434, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (287, 'CHOLESTYRAMINE', 'https://picsum.photos/id/593/400', 4305, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (288, 'LIPTRUZET', 'https://picsum.photos/id/170/400', 842, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (289, 'Coumarin', 'https://picsum.photos/id/263/400', 481, 'Rial');
insert into product (productID, productName, imageUrl, amount, currency) values (290, 'flawless by Sonya aloe BB creme NUDE SPF 20 Sunscreen', 'https://picsum.photos/id/359/400', 1985, 'Baht');
insert into product (productID, productName, imageUrl, amount, currency) values (291, 'Bayer Genuine Aspirin', 'https://picsum.photos/id/129/400', 672, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (292, 'Ondansetron', 'https://picsum.photos/id/389/400', 1414, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (293, 'Candida albicans', 'https://picsum.photos/id/346/400', 2476, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (294, 'Petasites Plantago', 'https://picsum.photos/id/552/400', 611, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (295, 'Strattera', 'https://picsum.photos/id/659/400', 3445, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (296, 'Evervescence Daily Facial Moisturizer Broad Spectrum SPF15 Sunscreen', 'https://picsum.photos/id/78/400', 2309, 'Dinar');
insert into product (productID, productName, imageUrl, amount, currency) values (297, 'Ropinirole Hydrochloride', 'https://picsum.photos/id/187/400', 661, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (298, 'Treatment Set TS347628', 'https://picsum.photos/id/507/400', 676, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (299, 'PANROSA Lavender Scented Hand', 'https://picsum.photos/id/354/400', 1138, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (300, 'Perphenazine', 'https://picsum.photos/id/589/400', 1490, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (301, 'Cold and Flu Relief', 'https://picsum.photos/id/294/400', 1731, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (302, 'Nystatin and Triamcinolone', 'https://picsum.photos/id/302/400', 1964, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (303, 'Xanax', 'https://picsum.photos/id/450/400', 1445, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (304, 'tussin cough', 'https://picsum.photos/id/44/400', 4451, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (305, 'Cefadroxil', 'https://picsum.photos/id/109/400', 4477, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (306, 'Standardized Perennial Rye Grass', 'https://picsum.photos/id/642/400', 2640, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (307, 'SENSODYNE', 'https://picsum.photos/id/354/400', 2905, 'Krona');
insert into product (productID, productName, imageUrl, amount, currency) values (308, 'Honey Dont Cough', 'https://picsum.photos/id/28/400', 2107, 'Zloty');
insert into product (productID, productName, imageUrl, amount, currency) values (309, 'Viagra', 'https://picsum.photos/id/489/400', 3962, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (310, 'PC511 ANTIMICROBIAL', 'https://picsum.photos/id/520/400', 617, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (311, 'Promethazine Hydrochloride', 'https://picsum.photos/id/92/400', 4603, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (312, 'Fire Ant', 'https://picsum.photos/id/420/400', 2513, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (313, 'sinus and allergy', 'https://picsum.photos/id/296/400', 3642, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (314, 'EGF Premium Whitening Milk', 'https://picsum.photos/id/662/400', 3080, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (315, 'Shopko Moisture SPF 15 Lip Balm', 'https://picsum.photos/id/469/400', 3488, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (316, 'Botanics Skin Calming Day Ultra Calm Sunscreen Broad Spectrum SPF 15', 'https://picsum.photos/id/612/400', 4972, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (317, 'Kidney Stone Clear', 'https://picsum.photos/id/404/400', 831, 'Lev');
insert into product (productID, productName, imageUrl, amount, currency) values (318, 'Equate Famotidine', 'https://picsum.photos/id/176/400', 3398, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (319, 'lisinopril', 'https://picsum.photos/id/191/400', 1942, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (320, 'Ramipril', 'https://picsum.photos/id/570/400', 4238, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (321, 'Isopto Homatropine', 'https://picsum.photos/id/27/400', 4846, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (322, 'Acarbose', 'https://picsum.photos/id/264/400', 1888, 'Franc');
insert into product (productID, productName, imageUrl, amount, currency) values (323, 'Brewers Yeast', 'https://picsum.photos/id/325/400', 34, 'Krone');
insert into product (productID, productName, imageUrl, amount, currency) values (324, 'Olay Fresh Effects BB', 'https://picsum.photos/id/297/400', 3830, 'Koruna');
insert into product (productID, productName, imageUrl, amount, currency) values (325, 'CRESTOR', 'https://picsum.photos/id/552/400', 4265, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (326, 'Ladys Choice Invisible Solid', 'https://picsum.photos/id/474/400', 2977, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (327, 'Gabapentin', 'https://picsum.photos/id/618/400', 2331, 'Balboa');
insert into product (productID, productName, imageUrl, amount, currency) values (328, 'adult cold, flu and sore throat', 'https://picsum.photos/id/287/400', 2681, 'Baht');
insert into product (productID, productName, imageUrl, amount, currency) values (329, 'Publix', 'https://picsum.photos/id/63/400', 4482, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (330, 'Chestnut', 'https://picsum.photos/id/330/400', 1086, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (331, 'Topiramate', 'https://picsum.photos/id/392/400', 1351, 'Lev');
insert into product (productID, productName, imageUrl, amount, currency) values (332, 'Health And Beyond Instant Hand Sanitizer Twin Pack', 'https://picsum.photos/id/452/400', 983, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (333, 'Lovastatin', 'https://picsum.photos/id/159/400', 170, 'Lempira');
insert into product (productID, productName, imageUrl, amount, currency) values (334, 'O-Cal Prenatal Vitamin', 'https://picsum.photos/id/529/400', 4712, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (335, 'Good Neighbor Pharmacy Sleep Aid', 'https://picsum.photos/id/698/400', 1411, 'Sol');
insert into product (productID, productName, imageUrl, amount, currency) values (336, 'Zyprexa', 'https://picsum.photos/id/578/400', 508, 'Baht');
insert into product (productID, productName, imageUrl, amount, currency) values (337, 'Purminerals 4 in 1 Makeup SPF 15 Tan', 'https://picsum.photos/id/397/400', 959, 'Franc');
insert into product (productID, productName, imageUrl, amount, currency) values (338, 'Prochlorperazine Maleate', 'https://picsum.photos/id/586/400', 1683, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (339, 'ck one all day perfection face makeup', 'https://picsum.photos/id/361/400', 1315, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (340, 'Cashmere', 'https://picsum.photos/id/505/400', 1123, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (341, 'RHEUMATISM', 'https://picsum.photos/id/62/400', 2071, 'Yen');
insert into product (productID, productName, imageUrl, amount, currency) values (342, 'Levetiracetam', 'https://picsum.photos/id/206/400', 1326, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (343, 'EX-LAX', 'https://picsum.photos/id/679/400', 1433, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (344, 'Beef Liver', 'https://picsum.photos/id/656/400', 2343, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (345, 'Petroleum Skin Protectant', 'https://picsum.photos/id/247/400', 3888, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (346, 'American Elm', 'https://picsum.photos/id/310/400', 2019, 'Franc');
insert into product (productID, productName, imageUrl, amount, currency) values (347, 'Ondansetron Hydrochloride', 'https://picsum.photos/id/633/400', 1176, 'Franc');
insert into product (productID, productName, imageUrl, amount, currency) values (348, 'DentiCare Pro-Gel', 'https://picsum.photos/id/522/400', 4519, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (349, 'Flu Relief Therapy Day Time', 'https://picsum.photos/id/470/400', 4215, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (350, 'Lisinopril', 'https://picsum.photos/id/465/400', 1961, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (351, 'Hydromorphone Hydrochloride', 'https://picsum.photos/id/633/400', 1194, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (352, 'miconazole 7', 'https://picsum.photos/id/652/400', 4703, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (353, 'ISOSORBIDE MONONITRATE', 'https://picsum.photos/id/593/400', 601, 'Pound');
insert into product (productID, productName, imageUrl, amount, currency) values (354, 'Aveeno Positively Radiant CC', 'https://picsum.photos/id/675/400', 4036, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (355, 'throat relief', 'https://picsum.photos/id/623/400', 214, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (356, 'Careone', 'https://picsum.photos/id/196/400', 4905, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (357, 'Tolnaftate', 'https://picsum.photos/id/691/400', 4725, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (358, 'Free Radical', 'https://picsum.photos/id/683/400', 611, 'Zloty');
insert into product (productID, productName, imageUrl, amount, currency) values (359, 'Acyclovir', 'https://picsum.photos/id/657/400', 1168, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (360, 'Family Care Clotrimazole Anti-Fungal Cream 1%', 'https://picsum.photos/id/385/400', 2218, 'Balboa');
insert into product (productID, productName, imageUrl, amount, currency) values (361, 'Capture Totale Radiance Restoring Serum Foundation SPF 15 030', 'https://picsum.photos/id/531/400', 1742, 'Quetzal');
insert into product (productID, productName, imageUrl, amount, currency) values (362, 'Navane', 'https://picsum.photos/id/299/400', 128, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (363, 'Dandruff', 'https://picsum.photos/id/571/400', 427, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (364, 'Fosinopril Sodium', 'https://picsum.photos/id/601/400', 4210, 'Shekel');
insert into product (productID, productName, imageUrl, amount, currency) values (365, 'SHISEIDO WHITE LUCENT BRIGHTENING PROTECTIVE W', 'https://picsum.photos/id/283/400', 923, 'Zloty');
insert into product (productID, productName, imageUrl, amount, currency) values (366, '4Life Enummi Protective Day Moisturizer', 'https://picsum.photos/id/482/400', 4890, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (367, 'Sterile Water', 'https://picsum.photos/id/234/400', 76, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (368, 'equaline sinus congestion and pain', 'https://picsum.photos/id/486/400', 1909, 'Bolivar');
insert into product (productID, productName, imageUrl, amount, currency) values (369, 'LBEL COULEUR LUXE AMPLIFIER XP', 'https://picsum.photos/id/515/400', 477, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (370, 'Butalbital, Acetaminophen, Caffeine, and Codeine Phosphate', 'https://picsum.photos/id/695/400', 2812, 'Zloty');
insert into product (productID, productName, imageUrl, amount, currency) values (371, 'Ibuprofen', 'https://picsum.photos/id/320/400', 3265, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (372, 'LAMIVUDINE', 'https://picsum.photos/id/243/400', 2066, 'Yen');
insert into product (productID, productName, imageUrl, amount, currency) values (373, 'MECLIZINE HYDROCHLORIDE', 'https://picsum.photos/id/505/400', 3930, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (374, 'Cyclophosphamide', 'https://picsum.photos/id/421/400', 4438, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (375, 'JUNIPERUS VIRGINIANA POLLEN', 'https://picsum.photos/id/70/400', 3436, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (376, 'Telmisartan and Amlodipine', 'https://picsum.photos/id/443/400', 780, 'Shilling');
insert into product (productID, productName, imageUrl, amount, currency) values (377, 'Tranxene', 'https://picsum.photos/id/630/400', 4619, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (378, 'Cefadroxil', 'https://picsum.photos/id/222/400', 3539, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (379, 'Levothyroxine Sodium', 'https://picsum.photos/id/55/400', 3279, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (380, 'NEUTRACETT', 'https://picsum.photos/id/611/400', 1316, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (381, 'equate vitamins a and d', 'https://picsum.photos/id/584/400', 4658, 'Cordoba');
insert into product (productID, productName, imageUrl, amount, currency) values (382, 'Fortical', 'https://picsum.photos/id/459/400', 2569, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (383, 'Cephalothecium', 'https://picsum.photos/id/496/400', 307, 'Quetzal');
insert into product (productID, productName, imageUrl, amount, currency) values (384, 'Para Grass Pollen', 'https://picsum.photos/id/595/400', 4158, 'Ringgit');
insert into product (productID, productName, imageUrl, amount, currency) values (385, 'OXYGEN', 'https://picsum.photos/id/42/400', 4199, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (386, 'Glycopyrrolate', 'https://picsum.photos/id/34/400', 2949, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (387, 'Purse Essentials hand sanitizer Anti-Bacterial Hand', 'https://picsum.photos/id/89/400', 4013, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (388, 'BUPRENORPHINE HYDROCHLORIDE', 'https://picsum.photos/id/552/400', 2457, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (389, 'Neosporin Plus Pain Relief', 'https://picsum.photos/id/346/400', 4706, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (390, 'CareOne Allergy Medication', 'https://picsum.photos/id/293/400', 779, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (391, 'Antabuse', 'https://picsum.photos/id/578/400', 2752, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (392, 'Treatment Set TS332850', 'https://picsum.photos/id/491/400', 4237, 'Som');
insert into product (productID, productName, imageUrl, amount, currency) values (393, 'MOIST MOISTURE BB', 'https://picsum.photos/id/690/400', 2048, 'Ringgit');
insert into product (productID, productName, imageUrl, amount, currency) values (394, 'Children Acetaminophen Grape Flavored Chewable', 'https://picsum.photos/id/617/400', 1363, 'Escudo');
insert into product (productID, productName, imageUrl, amount, currency) values (395, 'Bite Beauty', 'https://picsum.photos/id/191/400', 2995, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (396, 'MEND AID Antibacterial Adhesive Bandages', 'https://picsum.photos/id/497/400', 232, 'Franc');
insert into product (productID, productName, imageUrl, amount, currency) values (397, 'Pramipexole Dihydrochloride', 'https://picsum.photos/id/374/400', 379, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (398, 'MICRELL Antibacterial Ltn Sp', 'https://picsum.photos/id/250/400', 105, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (399, 'Venlafaxine Hydrochloride', 'https://picsum.photos/id/229/400', 4208, 'Yen');
insert into product (productID, productName, imageUrl, amount, currency) values (400, 'Naproxen', 'https://picsum.photos/id/192/400', 605, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (401, 'Metformin Hydrochloride', 'https://picsum.photos/id/690/400', 2820, 'Zloty');
insert into product (productID, productName, imageUrl, amount, currency) values (402, 'Metformin Hydrochloride', 'https://picsum.photos/id/182/400', 2375, 'Krona');
insert into product (productID, productName, imageUrl, amount, currency) values (403, 'Venofer', 'https://picsum.photos/id/692/400', 2616, 'Naira');
insert into product (productID, productName, imageUrl, amount, currency) values (404, 'Mirtazapine', 'https://picsum.photos/id/216/400', 4998, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (405, 'Levoxyl', 'https://picsum.photos/id/513/400', 1042, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (406, 'Aspergillus niger', 'https://picsum.photos/id/644/400', 1341, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (407, 'Quinapril Hydrochloride and Hydrochlorothiazide', 'https://picsum.photos/id/357/400', 4275, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (408, 'Slenderiix', 'https://picsum.photos/id/441/400', 326, 'Naira');
insert into product (productID, productName, imageUrl, amount, currency) values (409, 'zidovudine', 'https://picsum.photos/id/119/400', 3744, 'Manat');
insert into product (productID, productName, imageUrl, amount, currency) values (410, 'Lymphapar', 'https://picsum.photos/id/443/400', 3352, 'Rupee');
insert into product (productID, productName, imageUrl, amount, currency) values (411, 'Cranberry Spice Antibacterial Foaming Hand Wash', 'https://picsum.photos/id/663/400', 3730, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (412, 'Sumavel DosePro', 'https://picsum.photos/id/560/400', 4716, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (413, 'Genuine First Aid - Auto First Aid', 'https://picsum.photos/id/189/400', 3581, 'Dram');
insert into product (productID, productName, imageUrl, amount, currency) values (414, 'Physicians EZ Use B-12 Compliance', 'https://picsum.photos/id/478/400', 3127, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (415, 'Lab1796 Cholsterol Watch', 'https://picsum.photos/id/231/400', 4033, 'Lempira');
insert into product (productID, productName, imageUrl, amount, currency) values (416, 'Trazodone Hydrochloride', 'https://picsum.photos/id/526/400', 2438, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (417, 'Menstrual Relief', 'https://picsum.photos/id/694/400', 980, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (418, 'Topotecan hydrochloride', 'https://picsum.photos/id/180/400', 2793, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (419, 'Symphytum Officinale', 'https://picsum.photos/id/647/400', 118, 'Hryvnia');
insert into product (productID, productName, imageUrl, amount, currency) values (420, 'Vigofem Plus for Women', 'https://picsum.photos/id/110/400', 4123, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (421, 'Nitrostat', 'https://picsum.photos/id/366/400', 3049, 'Denar');
insert into product (productID, productName, imageUrl, amount, currency) values (422, 'Naproxen Sodium', 'https://picsum.photos/id/501/400', 4640, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (423, 'TUSSIN CF NIGHTTIME COUGH and COLD', 'https://picsum.photos/id/531/400', 410, 'Ringgit');
insert into product (productID, productName, imageUrl, amount, currency) values (424, 'Dexmethylphenidate Hydrochloride', 'https://picsum.photos/id/327/400', 3911, 'Afghani');
insert into product (productID, productName, imageUrl, amount, currency) values (425, 'Phytonadione', 'https://picsum.photos/id/551/400', 4132, 'Marka');
insert into product (productID, productName, imageUrl, amount, currency) values (426, 'LEADER Castor', 'https://picsum.photos/id/305/400', 2668, 'Rial');
insert into product (productID, productName, imageUrl, amount, currency) values (427, 'Hydralazine Hydrochloride', 'https://picsum.photos/id/334/400', 2480, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (428, 'Potassium Chloride', 'https://picsum.photos/id/645/400', 4174, 'Naira');
insert into product (productID, productName, imageUrl, amount, currency) values (429, 'Anticavity Fluoride Rinse', 'https://picsum.photos/id/420/400', 114, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (430, 'Alvesco', 'https://picsum.photos/id/34/400', 3504, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (431, 'Pre Post Surgery', 'https://picsum.photos/id/307/400', 1311, 'Sol');
insert into product (productID, productName, imageUrl, amount, currency) values (432, 'AVINZA', 'https://picsum.photos/id/310/400', 4908, 'Naira');
insert into product (productID, productName, imageUrl, amount, currency) values (433, 'Gabapentin', 'https://picsum.photos/id/206/400', 4271, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (434, 'Oxcarbazepine', 'https://picsum.photos/id/219/400', 1797, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (435, 'Hydrochlorothiazide', 'https://picsum.photos/id/105/400', 3962, 'Rial');
insert into product (productID, productName, imageUrl, amount, currency) values (436, 'HYVEE', 'https://picsum.photos/id/660/400', 2379, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (437, 'Dynarex Antifungal', 'https://picsum.photos/id/415/400', 1218, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (438, 'Mountain Cedar', 'https://picsum.photos/id/536/400', 1998, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (439, 'Degree', 'https://picsum.photos/id/15/400', 2803, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (440, 'ibuprofen', 'https://picsum.photos/id/208/400', 4781, 'Lempira');
insert into product (productID, productName, imageUrl, amount, currency) values (441, 'Adasuve', 'https://picsum.photos/id/209/400', 4322, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (442, 'Groundsel', 'https://picsum.photos/id/642/400', 3593, 'Dinar');
insert into product (productID, productName, imageUrl, amount, currency) values (443, 'Promethazine', 'https://picsum.photos/id/374/400', 3155, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (444, 'Phentermine Hydrochloride', 'https://picsum.photos/id/388/400', 3296, 'Rupee');
insert into product (productID, productName, imageUrl, amount, currency) values (445, 'hydrocodone bitartrate and acetaminophen', 'https://picsum.photos/id/435/400', 3202, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (446, 'Lysol', 'https://picsum.photos/id/53/400', 282, 'Koruna');
insert into product (productID, productName, imageUrl, amount, currency) values (447, 'Meperidine Hydrochloride', 'https://picsum.photos/id/486/400', 895, 'Krona');
insert into product (productID, productName, imageUrl, amount, currency) values (448, 'Care Bears Cotton Candy Antiseptic Hand Cleansing', 'https://picsum.photos/id/25/400', 3118, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (449, 'Loperamide Hydrochloride', 'https://picsum.photos/id/320/400', 4975, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (450, 'JUNIPERUS VIRGINIANA POLLEN', 'https://picsum.photos/id/656/400', 1878, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (451, 'Lenscale Quailbrush', 'https://picsum.photos/id/531/400', 4513, 'Baht');
insert into product (productID, productName, imageUrl, amount, currency) values (452, 'Minocycline Hydrochloride', 'https://picsum.photos/id/234/400', 2642, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (453, 'Propranolol Hydrochloride', 'https://picsum.photos/id/524/400', 975, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (454, 'Dry Cough', 'https://picsum.photos/id/157/400', 2947, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (455, 'Antibacterial Hand', 'https://picsum.photos/id/394/400', 1299, 'Krona');
insert into product (productID, productName, imageUrl, amount, currency) values (456, '07 Moisture Foundation SPF 15', 'https://picsum.photos/id/494/400', 539, 'Afghani');
insert into product (productID, productName, imageUrl, amount, currency) values (457, 'Ciprofloxacin', 'https://picsum.photos/id/530/400', 3933, 'Lek');
insert into product (productID, productName, imageUrl, amount, currency) values (458, 'NALOXONE HYDROCHLORIDE', 'https://picsum.photos/id/428/400', 685, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (459, 'LBEL HYDRATESS', 'https://picsum.photos/id/567/400', 2901, 'Shilling');
insert into product (productID, productName, imageUrl, amount, currency) values (460, 'Claforan', 'https://picsum.photos/id/586/400', 970, 'Yen');
insert into product (productID, productName, imageUrl, amount, currency) values (461, 'Cold and Flu', 'https://picsum.photos/id/678/400', 844, 'Kuna');
insert into product (productID, productName, imageUrl, amount, currency) values (462, 'Safeguard', 'https://picsum.photos/id/475/400', 4411, 'Franc');
insert into product (productID, productName, imageUrl, amount, currency) values (463, 'MAKESENSE', 'https://picsum.photos/id/225/400', 2288, 'Zloty');
insert into product (productID, productName, imageUrl, amount, currency) values (464, 'Nitrofurantoin Macrocrystals', 'https://picsum.photos/id/356/400', 465, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (465, 'Vinorelbine', 'https://picsum.photos/id/65/400', 472, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (466, 'Lidocaine Hydrochloride', 'https://picsum.photos/id/192/400', 409, 'Shekel');
insert into product (productID, productName, imageUrl, amount, currency) values (467, 'Kids Irritated Eye Relief', 'https://picsum.photos/id/380/400', 3558, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (468, 'REMERON', 'https://picsum.photos/id/683/400', 817, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (469, 'AQUAFRESH', 'https://picsum.photos/id/644/400', 2388, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (470, 'Potassium Chloride', 'https://picsum.photos/id/499/400', 422, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (471, 'AZITHROMYCIN', 'https://picsum.photos/id/133/400', 2946, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (472, 'Bug Bites - Itch Stopper', 'https://picsum.photos/id/452/400', 3233, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (473, 'Nisoldipine', 'https://picsum.photos/id/605/400', 1137, 'Ruble');
insert into product (productID, productName, imageUrl, amount, currency) values (474, 'Fairly Light Foundation SPF 15', 'https://picsum.photos/id/118/400', 119, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (475, 'Advanced Arnica', 'https://picsum.photos/id/28/400', 2844, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (476, 'Sprintec', 'https://picsum.photos/id/398/400', 532, 'Kuna');
insert into product (productID, productName, imageUrl, amount, currency) values (477, 'Zaditor', 'https://picsum.photos/id/479/400', 1195, 'Real');
insert into product (productID, productName, imageUrl, amount, currency) values (478, 'Tramadol Hydrochloride', 'https://picsum.photos/id/314/400', 1461, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (479, 'Ergomar', 'https://picsum.photos/id/348/400', 4537, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (480, 'Oxygen', 'https://picsum.photos/id/227/400', 993, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (481, 'Loxapine', 'https://picsum.photos/id/365/400', 3932, 'Cordoba');
insert into product (productID, productName, imageUrl, amount, currency) values (482, 'TRAMADOL HYDROCHLORIDE', 'https://picsum.photos/id/465/400', 3063, 'Franc');
insert into product (productID, productName, imageUrl, amount, currency) values (483, 'Oxybutynin Chloride', 'https://picsum.photos/id/489/400', 4525, 'Koruna');
insert into product (productID, productName, imageUrl, amount, currency) values (484, 'Aptivus', 'https://picsum.photos/id/174/400', 525, 'Hryvnia');
insert into product (productID, productName, imageUrl, amount, currency) values (485, 'PAXIL', 'https://picsum.photos/id/78/400', 3439, 'Rupiah');
insert into product (productID, productName, imageUrl, amount, currency) values (486, 'Givenchy Photo Perfexion Fluid Foundation SPF 20 Perfect Ivory Tint 1', 'https://picsum.photos/id/49/400', 1792, 'Krone');
insert into product (productID, productName, imageUrl, amount, currency) values (487, 'Rosmarinus Lavandula', 'https://picsum.photos/id/288/400', 4499, 'Kina');
insert into product (productID, productName, imageUrl, amount, currency) values (488, 'Dulcolax', 'https://picsum.photos/id/94/400', 187, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (489, 'TOLNAFTATE ANTIFUNGAL', 'https://picsum.photos/id/354/400', 3871, 'Hryvnia');
insert into product (productID, productName, imageUrl, amount, currency) values (490, 'Acetaminophen', 'https://picsum.photos/id/568/400', 4024, 'Rupee');
insert into product (productID, productName, imageUrl, amount, currency) values (491, 'ARNICA MONTANA WHOLE PLANT', 'https://picsum.photos/id/217/400', 3148, 'Euro');
insert into product (productID, productName, imageUrl, amount, currency) values (492, 'Benazepril Hydrochloride', 'https://picsum.photos/id/629/400', 3181, 'Dollar');
insert into product (productID, productName, imageUrl, amount, currency) values (493, 'BETTER THAN NATURE ESSENCE', 'https://picsum.photos/id/167/400', 4012, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (494, 'Budpak Petroleum', 'https://picsum.photos/id/173/400', 3465, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (495, 'Day and Night Cold', 'https://picsum.photos/id/390/400', 614, 'Peso');
insert into product (productID, productName, imageUrl, amount, currency) values (496, 'Ramipril', 'https://picsum.photos/id/155/400', 138, 'Yuan Renminbi');
insert into product (productID, productName, imageUrl, amount, currency) values (497, 'Smart Sense Tioconazole 1', 'https://picsum.photos/id/75/400', 2256, 'Lempira');
insert into product (productID, productName, imageUrl, amount, currency) values (498, 'HYOSCYAMINE SULFATE', 'https://picsum.photos/id/503/400', 3281, 'Bolivar');
insert into product (productID, productName, imageUrl, amount, currency) values (499, 'Alprazolam', 'https://picsum.photos/id/278/400', 1940, 'Koruna');
insert into product (productID, productName, imageUrl, amount, currency) values (500, 'ROPINIROLE HYDROCHLORIDE', 'https://picsum.photos/id/198/400', 3539, 'Rufiyaa');
